# Dockerfile.admin
FROM python:3.9.10-slim
WORKDIR /app
# Копируем файлы проекта и конфигурации
COPY ./admin /app/admin
COPY ./requirements.txt /app/requirements.txt
# Устанавливаем зависимости Python
RUN pip install --no-cache-dir -r requirements.txt
# Копируем конфигурационный файл
COPY ./admin/config.toml /app/config.toml
# Открываем порт 8501
EXPOSE 8500
#
ENTRYPOINT ["streamlit", "run", "admin/stream_app.py", "--server.port=8500"]
