"""Initial structure

Revision ID: 01
Revises: 
Create Date: 2024-10-24 15:20:06.711414

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('level', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_level_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('sber_id', sa.String(length=256), nullable=True),
    sa.Column('team_name', sa.String(length=256), nullable=True),
    sa.Column('role_level', sa.String(length=256), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('school21_nickname', sa.String(length=256), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_registered', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sber_id'),
    sa.UniqueConstraint('school21_nickname')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('admin_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('bot_debug_mode', sa.Boolean(), nullable=True),
    sa.Column('community_chat_id', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_chat_id')
    )
    with op.batch_alter_table('admin_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_settings_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_settings_id'))

    op.drop_table('admin_settings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('level', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_level_id'))

    op.drop_table('level')
    # ### end Alembic commands ###
