"""field_not_filled_correct

Revision ID: b652be3b6e80
Revises: 4599b953f3e7
Create Date: 2024-10-26 10:10:27.983131

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b652be3b6e80'
down_revision: Union[str, None] = '4599b953f3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('field_not_filled',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('field_not_filled',
               existing_type=sa.String(length=64),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
